api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        pagination_client_enabled: true
        pagination_items_per_page: 10 # Default value
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
